CREATE TABLE "User" (
    "Id" INTEGER NOT NULL CONSTRAINT "PK_User" PRIMARY KEY AUTOINCREMENT,
    "Login" TEXT COLLATE NOCASE NOT NULL,
    "PassHash" TEXT NOT NULL
);

CREATE UNIQUE INDEX "IX_User_Login" ON "User" ("Login");
